force-app/main/default/objects/Case/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseSLAManager.cls
/**
 * Created by bjohnson on 1/27/20.
 */

public with sharing class CaseSLAManager {
    List<Case> casesToProcess;

    public CaseSLAManager(List<Case> cases){
        this.casesToProcess = cases;
        procesSLA();
    }

    private void procesSLA(){
        for (Case c : casesToProcess){
            ISLAManager sLaManager = SLAFactory.getInstance(String.valueOf(c.Service_Type__c));
            c.SLA_Hours__c = sLaManager.getHours();
             }
    }

}