force-app/main/default/objects/SLAServiceSupport__mdt/SLAServiceSupport__mdt.object-meta.xml
<CustomObject>
    <label>SLAServiceSupport</label>
    <pluralLabel>SLAServiceSupportw</pluralLabel>
</CustomObject>

force-app/main/default/objects/SLAServiceSupport__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SLAFactory.cls
/**
 * Created by bjohnson on 1/27/20.
 */

public with sharing class SLAFactory {

    public static ISLAManager getInstance(String supportType){

        SLAServiceSupport__mdt support = [SELECT Class_Name__c
        FROM SLAServiceSupport__mdt
        WHERE Label =: supportType ];
        System.debug(support);

        Type t = Type.forName(support.Class_Name__c);
        ISLAManager manager = (ISLAManager)t.newInstance();
        return manager;
    }
}